default: &default
  adapter: postgresql
  host: <%= ENV["POSTGRES_HOST"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  port: <%= ENV["POSTGRES_PORT"] %>

development:
  <<: *default
production:
  <<: *default
test:
  <<: *default
  database: blog_api_test